[build.environment]
  HUGO_VERSION = "0.76.5"
[build]
  command = "hugo"
  publish = "public"
  functions = "functions"
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
[dev]
  command = " hugo serve"
