backend:
  name: git-gateway
  branch: master
  squash_merges: true

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

site_url: https://hildemorin.com

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "galleries" #
    label: "Galleries"
    folder: "content/galleries"
    create: false
    path: "{{slug}}/_index.md"
    media_folder: "./images"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Gallery Name", name: "galleryname", widget: "string", required: true}
      - {label: "Gallery Title", name: "gallerytitle", widget: "string", required: false}
      - {label: "Gallery Blurb", name: "galleryblurb", widget: "string", required: false}
      - {label: "Gallery Items", name: "galleryitems", widget: "list", fields: [
          {label: "Title", name: "title", widget: "string", required: true},
          {label: "Dimensions", name: "dimensions", widget: "string", required: true},
          {label: "Caption", name: "caption", widget: "markdown", required: true},
          {label: "Image Entry", name: "imageentry", widget: "image", allow_multiple: false, required: true},
          {label: "Image Scale", name: "scale", widget: "string", required: false},
          {label: "Image Icon", name: "imageicon", widget: "image", allow_multiple: false, required: true},
          {label: "Is Wide Icon?", name: "iswide", widget: "boolean", required: false},
          {label: "Price", name: "price", widget: "string", required: false}]}

  - name: "pages"
    label: "pages"
    files:
      - file: config.toml
        label: "Site Config"
        name: config
        fields:
          - label: "Site Parameters"
            name: "params"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Copyright Notice", name: "copyright", widget: "string"}
              - {label: "Site Updated Date", name: "updated", widget: "string"}
              - {label: "Site Keywords", name: "keywords", widget: "string"}
              - {label: "OpenGraph Image", name: "ogimage", widget: "string"}
              - {label: "Logo Image", name: "logoimage", widget: "string"}
              - {label: "Logo Text", name: "logotext", widget: "string"}
              - {label: "Menu Items", name: "menu", widget: "list", fields: [
                  {label: "Menu Link", name: "menulink", widget: "string"},
                  {label: "Menu Label", name: "menulabel", widget: "string"}]}
          - {label: "Base URL", name: "baseURL", widget: "string", required: false, default: ""}
          - {label: "Language Code", name: "languageCode", widget: "string"}
          - {label: "Relative URLs", name: "relativeURLs", widget: "boolean", default: true}
          - {label: "Theme", name: "theme", widget: "string", default: "hildemorin"}
          - {label: "Paginate", name: "paginate", widget: "number", default: 5, valueType: "int"}
          - {label: "Blog Summaries Length", name: "summaryLength", widget: "number", default: 5, valueType: "int"}
          - {label: "Google Analytics Site Code", name: "googleAnalytics", widget: "string"}
          - label: "Taxonomies"
            name: "taxonomies"
            widget: "object"
            fields:
              - {label: "Tag", name: "tag", widget: "string", default: "tags"}
      - file: content/_index.md
        label: "Home Page"
        name: "index"
        media_folder: "./images"
        fields:
          - {label: "Home Page Title", name: "title", widget: "string"}
          - {label: "Slider Images", name: "slider", widget: "list", fields: [
              {label: "Image URL", name: "imageurl", widget: "image", allow_multiple: false},
              {label: "Image Caption", name: "legendbottom", required: false, widget: "string"}]}
          - {label: "Galleries", name: "galleries", widget: "list", fields: [
              {label: "Image URL", name: "imageurl", widget: "image", allow_multiple: false},
              {label: "Image Caption", name: "caption", widget: "string"},
              {label: "Gallery Key", name: "page", widget: "string"}]}
          - {label: "Contact", name: "contact", widget: "object", fields: [
              {label: "Headline", name: "headline", widget: "string"},
              {label: "Contact Text", name: "description", widget: "markdown"},
              {label: "Location", name: "location", widget: "string"},
              {label: "Location Link", name: "locationlink", widget: "string"},
              {label: "Email", name: "email", widget: "string"},
              {label: "Photoblog", name: "photoblog", widget: "string"},
              {label: "Web Site", name: "web", widget: "string"}]}
          - {label: "Social Links", name: "sociallinks", widget: "list", fields: [
              {label: "Site Name", name: "sitename", widget: "string"},
              {label: "Site Link", name: "sitelink", widget: "string"},
              {label: "Site Icon", name: "icon", widget: "image", allow_multiple: false}]}
      - file: content/calendar/_index.md
        label: "Calendar"
        name: calendar
        fields:
          - {label: "Calendar Year", name: "calendaryear", widget: "string"}
          - {label: "Teaching Schedule", name: "teachingschedule", widget: "list", fields: [
              {label: "Date", name: "date", widget: "string"},
              {label: "Class Key", name: "classnamekey", widget: "select", options: ["curves", "yourownforest", "yourownvillage", "cityscape", "fracturedblocks", "bowlart"]},
              {label: "Class Name", name: "classname", widget: "string"},
              {label: "Class Details", name: "classdetails", widget: "markdown"},
              {label: "Class Contact Link", name: "classcontactlink", widget: "string"},
              {label: "Class Contact Name", name: "classcontactname", widget: "string"}]}
          - {label: "Exhibits", name: "exhibits", widget: "list", fields: [
              {label: "Exhibit Name", name: "exhibitname", widget: "string"},
              {label: "Exhibit Link", name: "exhibitlink", widget: "string"},
              {label: "Exhibit Info", name: "exhibitinfo", widget: "markdown"}]}
      - file: content/about/_index.md
        label: "About"
        name: "about"
        media_folder: "./images"
        fields:
          - {label: "Artist Banner Image", name: "artistbannerimage", widget: "image", allow_multiple: false}
          - {label: "Artist Quote", name: "artistquote", widget: "string"}
          - {label: "Artist Name", name: "artistname", widget: "string"}
          - {label: "Artist Statement", name: "artiststatement", widget: "markdown"}
          - {label: "Artist Publications", name: "artistpublications", widget: "list", fields: [
              {label: "Publication Info", name: "publication", widget: "string"}]}
          - {label: "Artist Assignments", name: "artistassignments", widget: "list", fields: [
              {label: "Assignment Info", name: "assignment", widget: "string"}]}
          - {label: "Artist Award Years", name: "artistawards", widget: "list", fields: [
              {label: "Award Year", name: "year", widget: "string"},
              {label: "Awards", name: "awards", widget: "list", fields: [
                {label: "Award Title", name: "award", widget: "string"},
                {label: "Award Presenter", name: "presenter", widget: "string"}]}]}
          - {label: "Artist Exhibits", name: "artistexhibits", widget: "list", fields: [
              {label: "Year", name: "year", widget: "string"},
              {label: "Exhibits", name: "exhibits", widget: "list"}]}
          - {label: "Artist Memberships", name: "artistmemberships", widget: "list", fields: [
              {label: "Organization", name: "org", widget: "string"},
              {label: "Organization Link", name: "orglink", widget: "string"}]}
      - file: content/classes/_index.md
        label: "Classes"
        name: "classes"
        media_folder: "./images"
        fields:
          - {label: "Classes Leading Intro", name: "classesintro", widget: "markdown"}
          - {label: "Classes", name: "classes", widget: "list", fields: [
              {label: "Class Key", name: "namekey", widget: "string"},
              {label: "Class Title", name: "title", widget: "string"},
              {label: "Class Duration", name: "duration", widget: "string"},
              {label: "Class Description", name: "description", widget: "markdown"},
              {label: "Class Thumbnail", name: "thumbnail", widget: "image", allow_multiple: false},
              {label: "Class Supply List Document", name: "supplylist", widget: "string"}]}
      - file: content/links/_index.md
        label: "Links"
        name: "links"
        fields:
          - {label: "My links title", name: "mylinkstitle", widget: "string"}
          - {label: "Links", name: "links", widget: "list", fields: [
              {label: "Title", name: "linktitle", widget: "string"},
              {label: "URL", name: "linkurl", widget: "string"}]}
