backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "pages"
    files:
      - file: config.toml
        label: "Site Config"
        name: config
        fields:
          - label: "Site Parameters"
            name: "params"
            widget: "object"
            fields:
              - {label: "Copyright Notice", name: "copyright", widget: "string"}
              - {label: "Site Updated Date", name: "updated", widget: "string"}
          - {label: "Base URL", name: "baseURL", widget: "string", required: false, default: ""}
          - {label: "Language Code", name: "languageCode", widget: "string"}
          - {label: "Relative URLs", name: "relativeURLs", widget: "boolean", default: true}
          - {label: "Theme", name: "theme", widget: "string", default: "hildemorin"}
          - {label: "Paginate", name: "paginate", widget: "number", default: 5, valueType: "int"}
          - label: "Taxonomies"
            name: "taxonomies"
            widget: "object"
            fields:
              - {label: "Tag", name: "tag", widget: "string", default: "tags"}
      - file: content/calendar/_index.md
        label: "Calendar"
        name: calendar
        fields:
          - {label: "Calendar Year", name: "calendaryear", widget: "string"}
          - {label: "Teaching Schedule", name: "teachingschedule", widget: "list", fields: [
              {label: "Date", name: "date", widget: "string"},
              {label: "Class Key", name: "classnamekey", widget: "select", options: ["curves", "yourownforest", "yourownvillage", "cityscape", "fracturedblocks", "bowlart"]},
              {label: "Class Name", name: "classname", widget: "string"},
              {label: "Class Details", name: "classdetails", widget: "markdown"},
              {label: "Class Contact Link", name: "classcontactlink", widget: "string"},
              {label: "Class Contact Name", name: "classcontactname", widget: "string"}]}
          - {label: "Exhibits", name: "exhibits", widget: "list", fields: [
              {label: "Exhibit Name", name: "exhibitname", widget: "string"},
              {label: "Exhibit Link", name: "exhibitlink", widget: "string"},
              {label: "Exhibit Info", name: "exhibitinfo", widget: "markdown"}]}
      - file: content/about/_index.md
        label: "About"
        name: "about"
        field:
          - {label: "Artist Quote", name: "artistquote", widget: "string"}
          - {label: "Artist Name", name: "artistname", widget: "string"}
          - {label: "Artist Statement", name: "artiststatement", widget: "markdown"}
          - {label: "Artist Publications", name: "artistpublications", widget: "list"}
          - {label: "Artist Assignments", name: "artistassignments", widget: "list"}
          - {label: "Artist Awards", name: "artistawards", widget: "list", fields: [
              {label: "Award Year", name: "year", widget: "string"},
              {label: "Awards", name: "awards", widget: "list", fields: [
                {label: "Award Title", name: "award", widget: "string"}
                {label: "Award Presenter", name: "presenter", widget: "string"}]}]}
          - {label: "Artist Exhibits", name: "artistexhibits", widget: "list", fields: [
              {label: "Year", name: "year", widget: "string"},
              {label: "Exhibits", name: "exhibits", widget: "list"}]}
          - {label: "Artist Memberships", name: "artistmemberships", widget: "list", fields: [
              {label: "Organization", name: "org", widget: "string"}
              {label: "Organization Link", name: "orglink", widget: "string"}
