name = "hildemorin"
license = "GPL"
licenselink = "https://github.com/jimmyangel/hildemorin/blob/master/themes/hildemorin/LICENSE.md"
description = "Cluster – Free Creative Portfolio Bootstrap Template"
homepage = "http://example.com/"
tags = ["portfolio", "blog"]
features = ["portfolio", "blog"]
min_version = "N/A"

[author]
  name = "Hilde Morin"
  homepage = "www.hildemorin.com"

[original]
  name = "Cluster"
  homepage = "https://readytheme.net/item/cluster-free-creative-portfolio-bootstrap-template/"
  repo = ""
